---
ansible_user: ansibleuser  # user with remote SSH access to each system
system_timezone: UTC
data_dir: /var/lib/rancher/k3s

k3s_version: v1.35.2+k3s1
gateway_api_version: v1.1.0
cilium_tag: v1.19.2
kube_vip_tag_version: v0.8.2
# kube_vip_cloud_provider_tag_version: main

cluster_domain: cluster.local
cluster_cidr: 10.52.0.0/16  # IP pool for pods
service_cidr: 10.53.0.0/16  # IP pool for services

cilium_iface: "{{ ansible_facts.default_ipv4.interface | default('eth0') }}"
cilium_mode: native  # native when nodes on same subnet or using bgp, else set routed
cilium_hubble: true  # enable hubble observability relay and ui

# Enable cilium bgp control plane for lb services and pod CIDRs
cilium_bgp: false
cilium_bgp_my_asn: 64513
cilium_bgp_peer_asn: 64512
cilium_bgp_peer_address: 192.168.30.1
cilium_bgp_lb_cidr: 192.168.31.0/24  # for cilium loadbalancer ipam

kube_vip_arp: true  # enable ARP broadcasts
kube_vip_bgp: false  # enable BGP advertisements
kube_vip_bgp_routerid: "{{ ansible_facts[cilium_iface]['ipv4']['address'] }}"  # BGP router ID
kube_vip_bgp_as: 64513  # BGP AS
kube_vip_bgp_peeraddress: 192.168.30.1  # upstream BGP peer's address
kube_vip_bgp_peeras: 64512  # upstream BGP peer's AS

# API VIP which will be configured on each master
apiserver_endpoint: 192.168.30.222

k3s_token: some-super-secret-string
k3s_node_ip: "{{ ansible_facts[cilium_iface]['ipv4']['address'] }}"

# Determines whether masters should run non-system workloads. Disable by explicitly setting false
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

# Common args for servers and agents:
extra_args: >-
  --data-dir "{{ data_dir }}"
  --node-ip "{{ k3s_node_ip }}"
  --node-name "{{ ansible_fqdn }}"

extra_server_args: >-
  {{ extra_args }}
  --flannel-backend "none"
  --disable-network-policy
  --disable-kube-proxy
  --cluster-domain "{{ cluster_domain }}"
  --cluster-cidr "{{ cluster_cidr }}"
  --service-cidr "{{ service_cidr }}"
  --tls-san "{{ apiserver_endpoint }}"
  --disable servicelb
  --disable traefik
  {% if k3s_master_taint %}
  --node-taint "node-role.kubernetes.io/control-plane:NoSchedule"
  {% endif %}

extra_agent_args: >-
  {{ extra_args }}


# Only enable this if you have set up your own container registry to act as a mirror / pull-through cache
# (harbor / nexus / docker's official registry / etc).
# Can be beneficial for larger dev/test environments (for example if you're getting rate limited by docker hub),
# or air-gapped environments where your nodes don't have internet access after the initial setup
# (which is still needed for downloading the k3s binary and such).
# k3s's documentation about private registries here: https://docs.k3s.io/installation/private-registry
custom_registries: false
# The registries can be authenticated or anonymous, depending on your registry server configuration.
# If they allow anonymous access, simply remove the following bit from custom_registries_yaml
#   configs:
#     "registry.domain.com":
#       auth:
#         username: yourusername
#         password: yourpassword
# The following is an example that pulls all images used in this playbook through your private registries.
# It also allows you to pull your own images from your private registry, without having to use imagePullSecrets
# in your deployments.
# If all you need is your own images and you don't care about caching the docker/quay/ghcr.io images,
# you can just remove those from the mirrors: section.
custom_registries_yaml: |
  mirrors:
    docker.io:
      endpoint:
        - "https://registry.domain.com/v2/dockerhub"
    quay.io:
      endpoint:
        - "https://registry.domain.com/v2/quayio"
    ghcr.io:
      endpoint:
        - "https://registry.domain.com/v2/ghcrio"
    registry.domain.com:
      endpoint:
        - "https://registry.domain.com"

  configs:
    "registry.domain.com":
      auth:
        username: yourusername
        password: yourpassword

# On some distros like Diet Pi, there is no dbus installed. dbus required by the default reboot command.
# Uncomment if you need a custom reboot command
# custom_reboot_command: /usr/sbin/shutdown -r now

# Only enable and configure these if you access the internet through a proxy
# proxy_env:
#   HTTP_PROXY: "http://proxy.domain.local:3128"
#   HTTPS_PROXY: "http://proxy.domain.local:3128"
#   NO_PROXY: "*.domain.local,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
