---
- name: Stop k3s-init
  ansible.builtin.systemd:
    name: k3s-init
    state: stopped
  failed_when: false

# k3s-init won't work if the port is already in use
- name: Stop k3s
  ansible.builtin.systemd:
    name: k3s
    state: stopped
  failed_when: false

- name: Reset failed state of k3s-init  # noqa command-instead-of-module
  # The systemd module does not support "reset-failed", so we need to resort to command.
  ansible.builtin.command: systemctl reset-failed k3s-init
  failed_when: false
  changed_when: false

- name: Deploy k3s HTTP proxy config
  ansible.builtin.include_tasks: http_proxy.yml
  when: proxy_env is defined

- name: Deploy kube-vip manifests
  ansible.builtin.include_tasks: vip.yml

- name: Initialize cluster via transient k3s-init service
  ansible.builtin.command:
    cmd: systemd-run -p RestartSec=2 -p Restart=on-failure --unit=k3s-init k3s server {{ server_init_args }}
    creates: "{{ systemd_dir }}/k3s-init.service"

- name: Verify all masters joined the cluster
  when: not ansible_check_mode
  block:
    - name: Verify all masters joined (check k3s-init.service if this fails)
      ansible.builtin.command:
        cmd: >-
          {{ k3s_kubectl_binary | default('k3s kubectl') }}
          get nodes
          -l 'node-role.kubernetes.io/control-plane'
          -o=jsonpath='{.items[*].metadata.name}'
      register: nodes
      until: >-
        nodes.rc == 0 and
        (nodes.stdout.split() | length) == (groups[group_name_master | default('master')] | length)
      retries: "{{ retry_count | default(20) }}"
      delay: 10
      changed_when: false
  always:
    - name: Save logs of k3s-init.service
      ansible.builtin.include_tasks: fetch_k3s_init_logs.yml
      when: log_destination
      vars:
        log_destination: >-
          {{ lookup('ansible.builtin.env', 'ANSIBLE_K3S_LOG_DIR', default=False) }}

    - name: Stop k3s-init service
      ansible.builtin.systemd:
        name: k3s-init
        state: stopped
      failed_when: false

- name: Install k3s service unit
  register: k3s_service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable and restart k3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: "{{ data_dir }}/server/node-token"

- name: Get node-token parent directory permissions
  ansible.builtin.stat:
    path: "{{ data_dir }}/server"
  register: p

- name: Widen node-token parent directory permissions
  ansible.builtin.file:
    path: "{{ data_dir }}/server"
    mode: g+rx,o+rx

- name: Read node-token from master
  ansible.builtin.slurp:
    src: "{{ data_dir }}/server/node-token"
  register: node_token

- name: Store master node-token
  ansible.builtin.set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token parent directory permissions
  ansible.builtin.file:
    path: "{{ data_dir }}/server"
    mode: "{{ p.stat.mode }}"

- name: Create .kube directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: u=rwx,g=rx,o=

- name: Copy kubeconfig to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    mode: u=rw,g=,o=

- name: Configure kubectl cluster to {{ endpoint_url }}
  ansible.builtin.command: >-
    {{ k3s_kubectl_binary | default('k3s kubectl') }} config set-cluster default
      --server={{ endpoint_url }}
      --kubeconfig {{ ansible_user_dir }}/.kube/config
  changed_when: true
  vars:
    endpoint_url: >-
      https://{{ apiserver_endpoint | ansible.utils.ipwrap }}:6443
# Deactivated linter rules:
#   - jinja[invalid]: As of version 6.6.0, ansible-lint complains that the input to ipwrap
#                     would be undefined. This will not be the case during playbook execution.
# noqa jinja[invalid]

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link
  when: k3s_create_kubectl_symlink | default(true) | bool

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
  when: k3s_create_crictl_symlink | default(true) | bool

- name: List manifests directory contents
  ansible.builtin.find:
    paths: "{{ data_dir }}/server/manifests"
    file_type: file
  register: k3s_server_manifests

- name: List manifests subdirectories
  ansible.builtin.find:
    paths: "{{ data_dir }}/server/manifests"
    file_type: directory
  register: k3s_server_manifests_directories

# These bootstrap manifests must be removed, otherwise k3s will keep
# re-applying them each time it starts.
- name: Remove bootstrap-only manifests
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ k3s_server_manifests.files }}"
    - "{{ k3s_server_manifests_directories.files }}"
  loop_control:
    label: "{{ item.path }}"
