---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: "{{ data_dir }}/server/manifests"
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
